# actionlint configuration file
# Defines custom runner labels for depot.dev runners

self-hosted-runner:
  labels:
    - depot-ubuntu-24.04-8
    - depot-ubuntu-24.04-16
    - depot-ubuntu-24.04-32
    - depot-ubuntu-22.04-8
    - depot-ubuntu-22.04-16
    - depot-ubuntu-22.04-32