run:
  timeout: 5m

  build-tags:
    - e2e
    - performance
    - probe
    - preupgrade
    - postupgrade
    - postdowngrade
    - istio

  skip-dirs:
    - pkg/client

  skip-files:
    - ".pb.go$"

linters:
  enable:
    - gosec
    - prealloc
    - unconvert
  disable:
    - errcheck

issues:
  exclude-rules:
    - path: test # Excludes /test, *_test.go etc.
      linters:
        - gosec
