// +build !ignore_autogenerated

/*
Copyright 2019 The Knative Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by conversion-gen. DO NOT EDIT.

package v1alpha1

import (
	unsafe "unsafe"

	v1 "k8s.io/api/core/v1"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
	apis "knative.dev/pkg/apis"
	duckv1alpha1 "knative.dev/pkg/apis/duck/v1alpha1"
	serving "knative.dev/serving/pkg/apis/internalversions/serving"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*AnnotationParseError)(nil), (*serving.AnnotationParseError)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_AnnotationParseError_To_serving_AnnotationParseError(a.(*AnnotationParseError), b.(*serving.AnnotationParseError), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*serving.AnnotationParseError)(nil), (*AnnotationParseError)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_serving_AnnotationParseError_To_v1alpha1_AnnotationParseError(a.(*serving.AnnotationParseError), b.(*AnnotationParseError), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*CannotConvertError)(nil), (*serving.CannotConvertError)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_CannotConvertError_To_serving_CannotConvertError(a.(*CannotConvertError), b.(*serving.CannotConvertError), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*serving.CannotConvertError)(nil), (*CannotConvertError)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_serving_CannotConvertError_To_v1alpha1_CannotConvertError(a.(*serving.CannotConvertError), b.(*CannotConvertError), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Configuration)(nil), (*serving.Configuration)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_Configuration_To_serving_Configuration(a.(*Configuration), b.(*serving.Configuration), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*serving.Configuration)(nil), (*Configuration)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_serving_Configuration_To_v1alpha1_Configuration(a.(*serving.Configuration), b.(*Configuration), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ConfigurationList)(nil), (*serving.ConfigurationList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ConfigurationList_To_serving_ConfigurationList(a.(*ConfigurationList), b.(*serving.ConfigurationList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*serving.ConfigurationList)(nil), (*ConfigurationList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_serving_ConfigurationList_To_v1alpha1_ConfigurationList(a.(*serving.ConfigurationList), b.(*ConfigurationList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ConfigurationSpec)(nil), (*serving.ConfigurationSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ConfigurationSpec_To_serving_ConfigurationSpec(a.(*ConfigurationSpec), b.(*serving.ConfigurationSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*serving.ConfigurationSpec)(nil), (*ConfigurationSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_serving_ConfigurationSpec_To_v1alpha1_ConfigurationSpec(a.(*serving.ConfigurationSpec), b.(*ConfigurationSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ConfigurationStatus)(nil), (*serving.ConfigurationStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ConfigurationStatus_To_serving_ConfigurationStatus(a.(*ConfigurationStatus), b.(*serving.ConfigurationStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*serving.ConfigurationStatus)(nil), (*ConfigurationStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_serving_ConfigurationStatus_To_v1alpha1_ConfigurationStatus(a.(*serving.ConfigurationStatus), b.(*ConfigurationStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ConfigurationStatusFields)(nil), (*serving.ConfigurationStatusFields)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ConfigurationStatusFields_To_serving_ConfigurationStatusFields(a.(*ConfigurationStatusFields), b.(*serving.ConfigurationStatusFields), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*serving.ConfigurationStatusFields)(nil), (*ConfigurationStatusFields)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_serving_ConfigurationStatusFields_To_v1alpha1_ConfigurationStatusFields(a.(*serving.ConfigurationStatusFields), b.(*ConfigurationStatusFields), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*LastPinnedParseError)(nil), (*serving.LastPinnedParseError)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_LastPinnedParseError_To_serving_LastPinnedParseError(a.(*LastPinnedParseError), b.(*serving.LastPinnedParseError), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*serving.LastPinnedParseError)(nil), (*LastPinnedParseError)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_serving_LastPinnedParseError_To_v1alpha1_LastPinnedParseError(a.(*serving.LastPinnedParseError), b.(*LastPinnedParseError), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ManualType)(nil), (*serving.ManualType)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ManualType_To_serving_ManualType(a.(*ManualType), b.(*serving.ManualType), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*serving.ManualType)(nil), (*ManualType)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_serving_ManualType_To_v1alpha1_ManualType(a.(*serving.ManualType), b.(*ManualType), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*PinnedType)(nil), (*serving.PinnedType)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_PinnedType_To_serving_PinnedType(a.(*PinnedType), b.(*serving.PinnedType), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*serving.PinnedType)(nil), (*PinnedType)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_serving_PinnedType_To_v1alpha1_PinnedType(a.(*serving.PinnedType), b.(*PinnedType), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ReleaseType)(nil), (*serving.ReleaseType)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ReleaseType_To_serving_ReleaseType(a.(*ReleaseType), b.(*serving.ReleaseType), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*serving.ReleaseType)(nil), (*ReleaseType)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_serving_ReleaseType_To_v1alpha1_ReleaseType(a.(*serving.ReleaseType), b.(*ReleaseType), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Revision)(nil), (*serving.Revision)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_Revision_To_serving_Revision(a.(*Revision), b.(*serving.Revision), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*serving.Revision)(nil), (*Revision)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_serving_Revision_To_v1alpha1_Revision(a.(*serving.Revision), b.(*Revision), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*RevisionList)(nil), (*serving.RevisionList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_RevisionList_To_serving_RevisionList(a.(*RevisionList), b.(*serving.RevisionList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*serving.RevisionList)(nil), (*RevisionList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_serving_RevisionList_To_v1alpha1_RevisionList(a.(*serving.RevisionList), b.(*RevisionList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*RevisionSpec)(nil), (*serving.RevisionSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_RevisionSpec_To_serving_RevisionSpec(a.(*RevisionSpec), b.(*serving.RevisionSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*serving.RevisionSpec)(nil), (*RevisionSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_serving_RevisionSpec_To_v1alpha1_RevisionSpec(a.(*serving.RevisionSpec), b.(*RevisionSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*RevisionStatus)(nil), (*serving.RevisionStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_RevisionStatus_To_serving_RevisionStatus(a.(*RevisionStatus), b.(*serving.RevisionStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*serving.RevisionStatus)(nil), (*RevisionStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_serving_RevisionStatus_To_v1alpha1_RevisionStatus(a.(*serving.RevisionStatus), b.(*RevisionStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*RevisionTemplateSpec)(nil), (*serving.RevisionTemplateSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_RevisionTemplateSpec_To_serving_RevisionTemplateSpec(a.(*RevisionTemplateSpec), b.(*serving.RevisionTemplateSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*serving.RevisionTemplateSpec)(nil), (*RevisionTemplateSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_serving_RevisionTemplateSpec_To_v1alpha1_RevisionTemplateSpec(a.(*serving.RevisionTemplateSpec), b.(*RevisionTemplateSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Route)(nil), (*serving.Route)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_Route_To_serving_Route(a.(*Route), b.(*serving.Route), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*serving.Route)(nil), (*Route)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_serving_Route_To_v1alpha1_Route(a.(*serving.Route), b.(*Route), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*RouteList)(nil), (*serving.RouteList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_RouteList_To_serving_RouteList(a.(*RouteList), b.(*serving.RouteList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*serving.RouteList)(nil), (*RouteList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_serving_RouteList_To_v1alpha1_RouteList(a.(*serving.RouteList), b.(*RouteList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*RouteSpec)(nil), (*serving.RouteSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_RouteSpec_To_serving_RouteSpec(a.(*RouteSpec), b.(*serving.RouteSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*serving.RouteSpec)(nil), (*RouteSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_serving_RouteSpec_To_v1alpha1_RouteSpec(a.(*serving.RouteSpec), b.(*RouteSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*RouteStatus)(nil), (*serving.RouteStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_RouteStatus_To_serving_RouteStatus(a.(*RouteStatus), b.(*serving.RouteStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*serving.RouteStatus)(nil), (*RouteStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_serving_RouteStatus_To_v1alpha1_RouteStatus(a.(*serving.RouteStatus), b.(*RouteStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*RouteStatusFields)(nil), (*serving.RouteStatusFields)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_RouteStatusFields_To_serving_RouteStatusFields(a.(*RouteStatusFields), b.(*serving.RouteStatusFields), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*serving.RouteStatusFields)(nil), (*RouteStatusFields)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_serving_RouteStatusFields_To_v1alpha1_RouteStatusFields(a.(*serving.RouteStatusFields), b.(*RouteStatusFields), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*RunLatestType)(nil), (*serving.RunLatestType)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_RunLatestType_To_serving_RunLatestType(a.(*RunLatestType), b.(*serving.RunLatestType), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*serving.RunLatestType)(nil), (*RunLatestType)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_serving_RunLatestType_To_v1alpha1_RunLatestType(a.(*serving.RunLatestType), b.(*RunLatestType), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Service)(nil), (*serving.Service)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_Service_To_serving_Service(a.(*Service), b.(*serving.Service), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*serving.Service)(nil), (*Service)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_serving_Service_To_v1alpha1_Service(a.(*serving.Service), b.(*Service), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ServiceList)(nil), (*serving.ServiceList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ServiceList_To_serving_ServiceList(a.(*ServiceList), b.(*serving.ServiceList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*serving.ServiceList)(nil), (*ServiceList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_serving_ServiceList_To_v1alpha1_ServiceList(a.(*serving.ServiceList), b.(*ServiceList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ServiceSpec)(nil), (*serving.ServiceSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ServiceSpec_To_serving_ServiceSpec(a.(*ServiceSpec), b.(*serving.ServiceSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*serving.ServiceSpec)(nil), (*ServiceSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_serving_ServiceSpec_To_v1alpha1_ServiceSpec(a.(*serving.ServiceSpec), b.(*ServiceSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ServiceStatus)(nil), (*serving.ServiceStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ServiceStatus_To_serving_ServiceStatus(a.(*ServiceStatus), b.(*serving.ServiceStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*serving.ServiceStatus)(nil), (*ServiceStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_serving_ServiceStatus_To_v1alpha1_ServiceStatus(a.(*serving.ServiceStatus), b.(*ServiceStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*TrafficTarget)(nil), (*serving.TrafficTarget)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_TrafficTarget_To_serving_TrafficTarget(a.(*TrafficTarget), b.(*serving.TrafficTarget), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*serving.TrafficTarget)(nil), (*TrafficTarget)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_serving_TrafficTarget_To_v1alpha1_TrafficTarget(a.(*serving.TrafficTarget), b.(*TrafficTarget), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*serving.RevisionSpec)(nil), (*RevisionSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_serving_RevisionSpec_To_v1alpha1_RevisionSpec(a.(*serving.RevisionSpec), b.(*RevisionSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*serving.TrafficTarget)(nil), (*TrafficTarget)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_serving_TrafficTarget_To_v1alpha1_TrafficTarget(a.(*serving.TrafficTarget), b.(*TrafficTarget), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*RevisionSpec)(nil), (*serving.RevisionSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_RevisionSpec_To_serving_RevisionSpec(a.(*RevisionSpec), b.(*serving.RevisionSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*TrafficTarget)(nil), (*serving.TrafficTarget)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_TrafficTarget_To_serving_TrafficTarget(a.(*TrafficTarget), b.(*serving.TrafficTarget), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1alpha1_AnnotationParseError_To_serving_AnnotationParseError(in *AnnotationParseError, out *serving.AnnotationParseError, s conversion.Scope) error {
	out.Type = in.Type
	out.Value = in.Value
	// TODO: Inefficient conversion - can we improve it?
	if err := s.Convert(&in.Err, &out.Err, 0); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_AnnotationParseError_To_serving_AnnotationParseError is an autogenerated conversion function.
func Convert_v1alpha1_AnnotationParseError_To_serving_AnnotationParseError(in *AnnotationParseError, out *serving.AnnotationParseError, s conversion.Scope) error {
	return autoConvert_v1alpha1_AnnotationParseError_To_serving_AnnotationParseError(in, out, s)
}

func autoConvert_serving_AnnotationParseError_To_v1alpha1_AnnotationParseError(in *serving.AnnotationParseError, out *AnnotationParseError, s conversion.Scope) error {
	out.Type = in.Type
	out.Value = in.Value
	// TODO: Inefficient conversion - can we improve it?
	if err := s.Convert(&in.Err, &out.Err, 0); err != nil {
		return err
	}
	return nil
}

// Convert_serving_AnnotationParseError_To_v1alpha1_AnnotationParseError is an autogenerated conversion function.
func Convert_serving_AnnotationParseError_To_v1alpha1_AnnotationParseError(in *serving.AnnotationParseError, out *AnnotationParseError, s conversion.Scope) error {
	return autoConvert_serving_AnnotationParseError_To_v1alpha1_AnnotationParseError(in, out, s)
}

func autoConvert_v1alpha1_CannotConvertError_To_serving_CannotConvertError(in *CannotConvertError, out *serving.CannotConvertError, s conversion.Scope) error {
	out.Message = in.Message
	out.Field = in.Field
	return nil
}

// Convert_v1alpha1_CannotConvertError_To_serving_CannotConvertError is an autogenerated conversion function.
func Convert_v1alpha1_CannotConvertError_To_serving_CannotConvertError(in *CannotConvertError, out *serving.CannotConvertError, s conversion.Scope) error {
	return autoConvert_v1alpha1_CannotConvertError_To_serving_CannotConvertError(in, out, s)
}

func autoConvert_serving_CannotConvertError_To_v1alpha1_CannotConvertError(in *serving.CannotConvertError, out *CannotConvertError, s conversion.Scope) error {
	out.Message = in.Message
	out.Field = in.Field
	return nil
}

// Convert_serving_CannotConvertError_To_v1alpha1_CannotConvertError is an autogenerated conversion function.
func Convert_serving_CannotConvertError_To_v1alpha1_CannotConvertError(in *serving.CannotConvertError, out *CannotConvertError, s conversion.Scope) error {
	return autoConvert_serving_CannotConvertError_To_v1alpha1_CannotConvertError(in, out, s)
}

func autoConvert_v1alpha1_Configuration_To_serving_Configuration(in *Configuration, out *serving.Configuration, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_ConfigurationSpec_To_serving_ConfigurationSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_ConfigurationStatus_To_serving_ConfigurationStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_Configuration_To_serving_Configuration is an autogenerated conversion function.
func Convert_v1alpha1_Configuration_To_serving_Configuration(in *Configuration, out *serving.Configuration, s conversion.Scope) error {
	return autoConvert_v1alpha1_Configuration_To_serving_Configuration(in, out, s)
}

func autoConvert_serving_Configuration_To_v1alpha1_Configuration(in *serving.Configuration, out *Configuration, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_serving_ConfigurationSpec_To_v1alpha1_ConfigurationSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_serving_ConfigurationStatus_To_v1alpha1_ConfigurationStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_serving_Configuration_To_v1alpha1_Configuration is an autogenerated conversion function.
func Convert_serving_Configuration_To_v1alpha1_Configuration(in *serving.Configuration, out *Configuration, s conversion.Scope) error {
	return autoConvert_serving_Configuration_To_v1alpha1_Configuration(in, out, s)
}

func autoConvert_v1alpha1_ConfigurationList_To_serving_ConfigurationList(in *ConfigurationList, out *serving.ConfigurationList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]serving.Configuration, len(*in))
		for i := range *in {
			if err := Convert_v1alpha1_Configuration_To_serving_Configuration(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Items = nil
	}
	return nil
}

// Convert_v1alpha1_ConfigurationList_To_serving_ConfigurationList is an autogenerated conversion function.
func Convert_v1alpha1_ConfigurationList_To_serving_ConfigurationList(in *ConfigurationList, out *serving.ConfigurationList, s conversion.Scope) error {
	return autoConvert_v1alpha1_ConfigurationList_To_serving_ConfigurationList(in, out, s)
}

func autoConvert_serving_ConfigurationList_To_v1alpha1_ConfigurationList(in *serving.ConfigurationList, out *ConfigurationList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Configuration, len(*in))
		for i := range *in {
			if err := Convert_serving_Configuration_To_v1alpha1_Configuration(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Items = nil
	}
	return nil
}

// Convert_serving_ConfigurationList_To_v1alpha1_ConfigurationList is an autogenerated conversion function.
func Convert_serving_ConfigurationList_To_v1alpha1_ConfigurationList(in *serving.ConfigurationList, out *ConfigurationList, s conversion.Scope) error {
	return autoConvert_serving_ConfigurationList_To_v1alpha1_ConfigurationList(in, out, s)
}

func autoConvert_v1alpha1_ConfigurationSpec_To_serving_ConfigurationSpec(in *ConfigurationSpec, out *serving.ConfigurationSpec, s conversion.Scope) error {
	out.DeprecatedGeneration = in.DeprecatedGeneration
	out.DeprecatedBuild = (*runtime.RawExtension)(unsafe.Pointer(in.DeprecatedBuild))
	if in.DeprecatedRevisionTemplate != nil {
		in, out := &in.DeprecatedRevisionTemplate, &out.DeprecatedRevisionTemplate
		*out = new(serving.RevisionTemplateSpec)
		if err := Convert_v1alpha1_RevisionTemplateSpec_To_serving_RevisionTemplateSpec(*in, *out, s); err != nil {
			return err
		}
	} else {
		out.DeprecatedRevisionTemplate = nil
	}
	if in.Template != nil {
		in, out := &in.Template, &out.Template
		*out = new(serving.RevisionTemplateSpec)
		if err := Convert_v1alpha1_RevisionTemplateSpec_To_serving_RevisionTemplateSpec(*in, *out, s); err != nil {
			return err
		}
	} else {
		out.Template = nil
	}
	return nil
}

// Convert_v1alpha1_ConfigurationSpec_To_serving_ConfigurationSpec is an autogenerated conversion function.
func Convert_v1alpha1_ConfigurationSpec_To_serving_ConfigurationSpec(in *ConfigurationSpec, out *serving.ConfigurationSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_ConfigurationSpec_To_serving_ConfigurationSpec(in, out, s)
}

func autoConvert_serving_ConfigurationSpec_To_v1alpha1_ConfigurationSpec(in *serving.ConfigurationSpec, out *ConfigurationSpec, s conversion.Scope) error {
	out.DeprecatedGeneration = in.DeprecatedGeneration
	out.DeprecatedBuild = (*runtime.RawExtension)(unsafe.Pointer(in.DeprecatedBuild))
	if in.DeprecatedRevisionTemplate != nil {
		in, out := &in.DeprecatedRevisionTemplate, &out.DeprecatedRevisionTemplate
		*out = new(RevisionTemplateSpec)
		if err := Convert_serving_RevisionTemplateSpec_To_v1alpha1_RevisionTemplateSpec(*in, *out, s); err != nil {
			return err
		}
	} else {
		out.DeprecatedRevisionTemplate = nil
	}
	if in.Template != nil {
		in, out := &in.Template, &out.Template
		*out = new(RevisionTemplateSpec)
		if err := Convert_serving_RevisionTemplateSpec_To_v1alpha1_RevisionTemplateSpec(*in, *out, s); err != nil {
			return err
		}
	} else {
		out.Template = nil
	}
	return nil
}

// Convert_serving_ConfigurationSpec_To_v1alpha1_ConfigurationSpec is an autogenerated conversion function.
func Convert_serving_ConfigurationSpec_To_v1alpha1_ConfigurationSpec(in *serving.ConfigurationSpec, out *ConfigurationSpec, s conversion.Scope) error {
	return autoConvert_serving_ConfigurationSpec_To_v1alpha1_ConfigurationSpec(in, out, s)
}

func autoConvert_v1alpha1_ConfigurationStatus_To_serving_ConfigurationStatus(in *ConfigurationStatus, out *serving.ConfigurationStatus, s conversion.Scope) error {
	out.Status = in.Status
	if err := Convert_v1alpha1_ConfigurationStatusFields_To_serving_ConfigurationStatusFields(&in.ConfigurationStatusFields, &out.ConfigurationStatusFields, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_ConfigurationStatus_To_serving_ConfigurationStatus is an autogenerated conversion function.
func Convert_v1alpha1_ConfigurationStatus_To_serving_ConfigurationStatus(in *ConfigurationStatus, out *serving.ConfigurationStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_ConfigurationStatus_To_serving_ConfigurationStatus(in, out, s)
}

func autoConvert_serving_ConfigurationStatus_To_v1alpha1_ConfigurationStatus(in *serving.ConfigurationStatus, out *ConfigurationStatus, s conversion.Scope) error {
	out.Status = in.Status
	if err := Convert_serving_ConfigurationStatusFields_To_v1alpha1_ConfigurationStatusFields(&in.ConfigurationStatusFields, &out.ConfigurationStatusFields, s); err != nil {
		return err
	}
	return nil
}

// Convert_serving_ConfigurationStatus_To_v1alpha1_ConfigurationStatus is an autogenerated conversion function.
func Convert_serving_ConfigurationStatus_To_v1alpha1_ConfigurationStatus(in *serving.ConfigurationStatus, out *ConfigurationStatus, s conversion.Scope) error {
	return autoConvert_serving_ConfigurationStatus_To_v1alpha1_ConfigurationStatus(in, out, s)
}

func autoConvert_v1alpha1_ConfigurationStatusFields_To_serving_ConfigurationStatusFields(in *ConfigurationStatusFields, out *serving.ConfigurationStatusFields, s conversion.Scope) error {
	out.LatestReadyRevisionName = in.LatestReadyRevisionName
	out.LatestCreatedRevisionName = in.LatestCreatedRevisionName
	return nil
}

// Convert_v1alpha1_ConfigurationStatusFields_To_serving_ConfigurationStatusFields is an autogenerated conversion function.
func Convert_v1alpha1_ConfigurationStatusFields_To_serving_ConfigurationStatusFields(in *ConfigurationStatusFields, out *serving.ConfigurationStatusFields, s conversion.Scope) error {
	return autoConvert_v1alpha1_ConfigurationStatusFields_To_serving_ConfigurationStatusFields(in, out, s)
}

func autoConvert_serving_ConfigurationStatusFields_To_v1alpha1_ConfigurationStatusFields(in *serving.ConfigurationStatusFields, out *ConfigurationStatusFields, s conversion.Scope) error {
	out.LatestReadyRevisionName = in.LatestReadyRevisionName
	out.LatestCreatedRevisionName = in.LatestCreatedRevisionName
	return nil
}

// Convert_serving_ConfigurationStatusFields_To_v1alpha1_ConfigurationStatusFields is an autogenerated conversion function.
func Convert_serving_ConfigurationStatusFields_To_v1alpha1_ConfigurationStatusFields(in *serving.ConfigurationStatusFields, out *ConfigurationStatusFields, s conversion.Scope) error {
	return autoConvert_serving_ConfigurationStatusFields_To_v1alpha1_ConfigurationStatusFields(in, out, s)
}

func autoConvert_v1alpha1_LastPinnedParseError_To_serving_LastPinnedParseError(in *LastPinnedParseError, out *serving.LastPinnedParseError, s conversion.Scope) error {
	out.Type = in.Type
	out.Value = in.Value
	// TODO: Inefficient conversion - can we improve it?
	if err := s.Convert(&in.Err, &out.Err, 0); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_LastPinnedParseError_To_serving_LastPinnedParseError is an autogenerated conversion function.
func Convert_v1alpha1_LastPinnedParseError_To_serving_LastPinnedParseError(in *LastPinnedParseError, out *serving.LastPinnedParseError, s conversion.Scope) error {
	return autoConvert_v1alpha1_LastPinnedParseError_To_serving_LastPinnedParseError(in, out, s)
}

func autoConvert_serving_LastPinnedParseError_To_v1alpha1_LastPinnedParseError(in *serving.LastPinnedParseError, out *LastPinnedParseError, s conversion.Scope) error {
	out.Type = in.Type
	out.Value = in.Value
	// TODO: Inefficient conversion - can we improve it?
	if err := s.Convert(&in.Err, &out.Err, 0); err != nil {
		return err
	}
	return nil
}

// Convert_serving_LastPinnedParseError_To_v1alpha1_LastPinnedParseError is an autogenerated conversion function.
func Convert_serving_LastPinnedParseError_To_v1alpha1_LastPinnedParseError(in *serving.LastPinnedParseError, out *LastPinnedParseError, s conversion.Scope) error {
	return autoConvert_serving_LastPinnedParseError_To_v1alpha1_LastPinnedParseError(in, out, s)
}

func autoConvert_v1alpha1_ManualType_To_serving_ManualType(in *ManualType, out *serving.ManualType, s conversion.Scope) error {
	return nil
}

// Convert_v1alpha1_ManualType_To_serving_ManualType is an autogenerated conversion function.
func Convert_v1alpha1_ManualType_To_serving_ManualType(in *ManualType, out *serving.ManualType, s conversion.Scope) error {
	return autoConvert_v1alpha1_ManualType_To_serving_ManualType(in, out, s)
}

func autoConvert_serving_ManualType_To_v1alpha1_ManualType(in *serving.ManualType, out *ManualType, s conversion.Scope) error {
	return nil
}

// Convert_serving_ManualType_To_v1alpha1_ManualType is an autogenerated conversion function.
func Convert_serving_ManualType_To_v1alpha1_ManualType(in *serving.ManualType, out *ManualType, s conversion.Scope) error {
	return autoConvert_serving_ManualType_To_v1alpha1_ManualType(in, out, s)
}

func autoConvert_v1alpha1_PinnedType_To_serving_PinnedType(in *PinnedType, out *serving.PinnedType, s conversion.Scope) error {
	out.RevisionName = in.RevisionName
	if err := Convert_v1alpha1_ConfigurationSpec_To_serving_ConfigurationSpec(&in.Configuration, &out.Configuration, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_PinnedType_To_serving_PinnedType is an autogenerated conversion function.
func Convert_v1alpha1_PinnedType_To_serving_PinnedType(in *PinnedType, out *serving.PinnedType, s conversion.Scope) error {
	return autoConvert_v1alpha1_PinnedType_To_serving_PinnedType(in, out, s)
}

func autoConvert_serving_PinnedType_To_v1alpha1_PinnedType(in *serving.PinnedType, out *PinnedType, s conversion.Scope) error {
	out.RevisionName = in.RevisionName
	if err := Convert_serving_ConfigurationSpec_To_v1alpha1_ConfigurationSpec(&in.Configuration, &out.Configuration, s); err != nil {
		return err
	}
	return nil
}

// Convert_serving_PinnedType_To_v1alpha1_PinnedType is an autogenerated conversion function.
func Convert_serving_PinnedType_To_v1alpha1_PinnedType(in *serving.PinnedType, out *PinnedType, s conversion.Scope) error {
	return autoConvert_serving_PinnedType_To_v1alpha1_PinnedType(in, out, s)
}

func autoConvert_v1alpha1_ReleaseType_To_serving_ReleaseType(in *ReleaseType, out *serving.ReleaseType, s conversion.Scope) error {
	out.Revisions = *(*[]string)(unsafe.Pointer(&in.Revisions))
	out.RolloutPercent = in.RolloutPercent
	if err := Convert_v1alpha1_ConfigurationSpec_To_serving_ConfigurationSpec(&in.Configuration, &out.Configuration, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_ReleaseType_To_serving_ReleaseType is an autogenerated conversion function.
func Convert_v1alpha1_ReleaseType_To_serving_ReleaseType(in *ReleaseType, out *serving.ReleaseType, s conversion.Scope) error {
	return autoConvert_v1alpha1_ReleaseType_To_serving_ReleaseType(in, out, s)
}

func autoConvert_serving_ReleaseType_To_v1alpha1_ReleaseType(in *serving.ReleaseType, out *ReleaseType, s conversion.Scope) error {
	out.Revisions = *(*[]string)(unsafe.Pointer(&in.Revisions))
	out.RolloutPercent = in.RolloutPercent
	if err := Convert_serving_ConfigurationSpec_To_v1alpha1_ConfigurationSpec(&in.Configuration, &out.Configuration, s); err != nil {
		return err
	}
	return nil
}

// Convert_serving_ReleaseType_To_v1alpha1_ReleaseType is an autogenerated conversion function.
func Convert_serving_ReleaseType_To_v1alpha1_ReleaseType(in *serving.ReleaseType, out *ReleaseType, s conversion.Scope) error {
	return autoConvert_serving_ReleaseType_To_v1alpha1_ReleaseType(in, out, s)
}

func autoConvert_v1alpha1_Revision_To_serving_Revision(in *Revision, out *serving.Revision, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_RevisionSpec_To_serving_RevisionSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_RevisionStatus_To_serving_RevisionStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_Revision_To_serving_Revision is an autogenerated conversion function.
func Convert_v1alpha1_Revision_To_serving_Revision(in *Revision, out *serving.Revision, s conversion.Scope) error {
	return autoConvert_v1alpha1_Revision_To_serving_Revision(in, out, s)
}

func autoConvert_serving_Revision_To_v1alpha1_Revision(in *serving.Revision, out *Revision, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_serving_RevisionSpec_To_v1alpha1_RevisionSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_serving_RevisionStatus_To_v1alpha1_RevisionStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_serving_Revision_To_v1alpha1_Revision is an autogenerated conversion function.
func Convert_serving_Revision_To_v1alpha1_Revision(in *serving.Revision, out *Revision, s conversion.Scope) error {
	return autoConvert_serving_Revision_To_v1alpha1_Revision(in, out, s)
}

func autoConvert_v1alpha1_RevisionList_To_serving_RevisionList(in *RevisionList, out *serving.RevisionList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]serving.Revision, len(*in))
		for i := range *in {
			if err := Convert_v1alpha1_Revision_To_serving_Revision(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Items = nil
	}
	return nil
}

// Convert_v1alpha1_RevisionList_To_serving_RevisionList is an autogenerated conversion function.
func Convert_v1alpha1_RevisionList_To_serving_RevisionList(in *RevisionList, out *serving.RevisionList, s conversion.Scope) error {
	return autoConvert_v1alpha1_RevisionList_To_serving_RevisionList(in, out, s)
}

func autoConvert_serving_RevisionList_To_v1alpha1_RevisionList(in *serving.RevisionList, out *RevisionList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Revision, len(*in))
		for i := range *in {
			if err := Convert_serving_Revision_To_v1alpha1_Revision(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Items = nil
	}
	return nil
}

// Convert_serving_RevisionList_To_v1alpha1_RevisionList is an autogenerated conversion function.
func Convert_serving_RevisionList_To_v1alpha1_RevisionList(in *serving.RevisionList, out *RevisionList, s conversion.Scope) error {
	return autoConvert_serving_RevisionList_To_v1alpha1_RevisionList(in, out, s)
}

func autoConvert_v1alpha1_RevisionSpec_To_serving_RevisionSpec(in *RevisionSpec, out *serving.RevisionSpec, s conversion.Scope) error {
	// WARNING: in.RevisionSpec requires manual conversion: does not exist in peer-type
	out.DeprecatedGeneration = in.DeprecatedGeneration
	out.DeprecatedServingState = serving.DeprecatedRevisionServingStateType(in.DeprecatedServingState)
	out.DeprecatedConcurrencyModel = serving.DeprecatedRevisionRequestConcurrencyModelType(in.DeprecatedConcurrencyModel)
	out.DeprecatedBuildName = in.DeprecatedBuildName
	out.DeprecatedBuildRef = (*v1.ObjectReference)(unsafe.Pointer(in.DeprecatedBuildRef))
	out.DeprecatedContainer = (*v1.Container)(unsafe.Pointer(in.DeprecatedContainer))
	return nil
}

func autoConvert_serving_RevisionSpec_To_v1alpha1_RevisionSpec(in *serving.RevisionSpec, out *RevisionSpec, s conversion.Scope) error {
	// WARNING: in.PodSpec requires manual conversion: does not exist in peer-type
	// WARNING: in.ContainerConcurrency requires manual conversion: does not exist in peer-type
	// WARNING: in.TimeoutSeconds requires manual conversion: does not exist in peer-type
	out.DeprecatedGeneration = in.DeprecatedGeneration
	out.DeprecatedServingState = DeprecatedRevisionServingStateType(in.DeprecatedServingState)
	out.DeprecatedConcurrencyModel = DeprecatedRevisionRequestConcurrencyModelType(in.DeprecatedConcurrencyModel)
	out.DeprecatedBuildName = in.DeprecatedBuildName
	out.DeprecatedBuildRef = (*v1.ObjectReference)(unsafe.Pointer(in.DeprecatedBuildRef))
	out.DeprecatedContainer = (*v1.Container)(unsafe.Pointer(in.DeprecatedContainer))
	return nil
}

func autoConvert_v1alpha1_RevisionStatus_To_serving_RevisionStatus(in *RevisionStatus, out *serving.RevisionStatus, s conversion.Scope) error {
	out.Status = in.Status
	out.ServiceName = in.ServiceName
	out.LogURL = in.LogURL
	out.ImageDigest = in.ImageDigest
	return nil
}

// Convert_v1alpha1_RevisionStatus_To_serving_RevisionStatus is an autogenerated conversion function.
func Convert_v1alpha1_RevisionStatus_To_serving_RevisionStatus(in *RevisionStatus, out *serving.RevisionStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_RevisionStatus_To_serving_RevisionStatus(in, out, s)
}

func autoConvert_serving_RevisionStatus_To_v1alpha1_RevisionStatus(in *serving.RevisionStatus, out *RevisionStatus, s conversion.Scope) error {
	out.Status = in.Status
	out.ServiceName = in.ServiceName
	out.LogURL = in.LogURL
	out.ImageDigest = in.ImageDigest
	return nil
}

// Convert_serving_RevisionStatus_To_v1alpha1_RevisionStatus is an autogenerated conversion function.
func Convert_serving_RevisionStatus_To_v1alpha1_RevisionStatus(in *serving.RevisionStatus, out *RevisionStatus, s conversion.Scope) error {
	return autoConvert_serving_RevisionStatus_To_v1alpha1_RevisionStatus(in, out, s)
}

func autoConvert_v1alpha1_RevisionTemplateSpec_To_serving_RevisionTemplateSpec(in *RevisionTemplateSpec, out *serving.RevisionTemplateSpec, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_RevisionSpec_To_serving_RevisionSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_RevisionTemplateSpec_To_serving_RevisionTemplateSpec is an autogenerated conversion function.
func Convert_v1alpha1_RevisionTemplateSpec_To_serving_RevisionTemplateSpec(in *RevisionTemplateSpec, out *serving.RevisionTemplateSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_RevisionTemplateSpec_To_serving_RevisionTemplateSpec(in, out, s)
}

func autoConvert_serving_RevisionTemplateSpec_To_v1alpha1_RevisionTemplateSpec(in *serving.RevisionTemplateSpec, out *RevisionTemplateSpec, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_serving_RevisionSpec_To_v1alpha1_RevisionSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert_serving_RevisionTemplateSpec_To_v1alpha1_RevisionTemplateSpec is an autogenerated conversion function.
func Convert_serving_RevisionTemplateSpec_To_v1alpha1_RevisionTemplateSpec(in *serving.RevisionTemplateSpec, out *RevisionTemplateSpec, s conversion.Scope) error {
	return autoConvert_serving_RevisionTemplateSpec_To_v1alpha1_RevisionTemplateSpec(in, out, s)
}

func autoConvert_v1alpha1_Route_To_serving_Route(in *Route, out *serving.Route, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_RouteSpec_To_serving_RouteSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_RouteStatus_To_serving_RouteStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_Route_To_serving_Route is an autogenerated conversion function.
func Convert_v1alpha1_Route_To_serving_Route(in *Route, out *serving.Route, s conversion.Scope) error {
	return autoConvert_v1alpha1_Route_To_serving_Route(in, out, s)
}

func autoConvert_serving_Route_To_v1alpha1_Route(in *serving.Route, out *Route, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_serving_RouteSpec_To_v1alpha1_RouteSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_serving_RouteStatus_To_v1alpha1_RouteStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_serving_Route_To_v1alpha1_Route is an autogenerated conversion function.
func Convert_serving_Route_To_v1alpha1_Route(in *serving.Route, out *Route, s conversion.Scope) error {
	return autoConvert_serving_Route_To_v1alpha1_Route(in, out, s)
}

func autoConvert_v1alpha1_RouteList_To_serving_RouteList(in *RouteList, out *serving.RouteList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]serving.Route, len(*in))
		for i := range *in {
			if err := Convert_v1alpha1_Route_To_serving_Route(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Items = nil
	}
	return nil
}

// Convert_v1alpha1_RouteList_To_serving_RouteList is an autogenerated conversion function.
func Convert_v1alpha1_RouteList_To_serving_RouteList(in *RouteList, out *serving.RouteList, s conversion.Scope) error {
	return autoConvert_v1alpha1_RouteList_To_serving_RouteList(in, out, s)
}

func autoConvert_serving_RouteList_To_v1alpha1_RouteList(in *serving.RouteList, out *RouteList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Route, len(*in))
		for i := range *in {
			if err := Convert_serving_Route_To_v1alpha1_Route(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Items = nil
	}
	return nil
}

// Convert_serving_RouteList_To_v1alpha1_RouteList is an autogenerated conversion function.
func Convert_serving_RouteList_To_v1alpha1_RouteList(in *serving.RouteList, out *RouteList, s conversion.Scope) error {
	return autoConvert_serving_RouteList_To_v1alpha1_RouteList(in, out, s)
}

func autoConvert_v1alpha1_RouteSpec_To_serving_RouteSpec(in *RouteSpec, out *serving.RouteSpec, s conversion.Scope) error {
	out.DeprecatedGeneration = in.DeprecatedGeneration
	if in.Traffic != nil {
		in, out := &in.Traffic, &out.Traffic
		*out = make([]serving.TrafficTarget, len(*in))
		for i := range *in {
			if err := Convert_v1alpha1_TrafficTarget_To_serving_TrafficTarget(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Traffic = nil
	}
	return nil
}

// Convert_v1alpha1_RouteSpec_To_serving_RouteSpec is an autogenerated conversion function.
func Convert_v1alpha1_RouteSpec_To_serving_RouteSpec(in *RouteSpec, out *serving.RouteSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_RouteSpec_To_serving_RouteSpec(in, out, s)
}

func autoConvert_serving_RouteSpec_To_v1alpha1_RouteSpec(in *serving.RouteSpec, out *RouteSpec, s conversion.Scope) error {
	out.DeprecatedGeneration = in.DeprecatedGeneration
	if in.Traffic != nil {
		in, out := &in.Traffic, &out.Traffic
		*out = make([]TrafficTarget, len(*in))
		for i := range *in {
			if err := Convert_serving_TrafficTarget_To_v1alpha1_TrafficTarget(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Traffic = nil
	}
	return nil
}

// Convert_serving_RouteSpec_To_v1alpha1_RouteSpec is an autogenerated conversion function.
func Convert_serving_RouteSpec_To_v1alpha1_RouteSpec(in *serving.RouteSpec, out *RouteSpec, s conversion.Scope) error {
	return autoConvert_serving_RouteSpec_To_v1alpha1_RouteSpec(in, out, s)
}

func autoConvert_v1alpha1_RouteStatus_To_serving_RouteStatus(in *RouteStatus, out *serving.RouteStatus, s conversion.Scope) error {
	out.Status = in.Status
	if err := Convert_v1alpha1_RouteStatusFields_To_serving_RouteStatusFields(&in.RouteStatusFields, &out.RouteStatusFields, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_RouteStatus_To_serving_RouteStatus is an autogenerated conversion function.
func Convert_v1alpha1_RouteStatus_To_serving_RouteStatus(in *RouteStatus, out *serving.RouteStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_RouteStatus_To_serving_RouteStatus(in, out, s)
}

func autoConvert_serving_RouteStatus_To_v1alpha1_RouteStatus(in *serving.RouteStatus, out *RouteStatus, s conversion.Scope) error {
	out.Status = in.Status
	if err := Convert_serving_RouteStatusFields_To_v1alpha1_RouteStatusFields(&in.RouteStatusFields, &out.RouteStatusFields, s); err != nil {
		return err
	}
	return nil
}

// Convert_serving_RouteStatus_To_v1alpha1_RouteStatus is an autogenerated conversion function.
func Convert_serving_RouteStatus_To_v1alpha1_RouteStatus(in *serving.RouteStatus, out *RouteStatus, s conversion.Scope) error {
	return autoConvert_serving_RouteStatus_To_v1alpha1_RouteStatus(in, out, s)
}

func autoConvert_v1alpha1_RouteStatusFields_To_serving_RouteStatusFields(in *RouteStatusFields, out *serving.RouteStatusFields, s conversion.Scope) error {
	out.URL = (*apis.URL)(unsafe.Pointer(in.URL))
	out.DeprecatedDomain = in.DeprecatedDomain
	out.DeprecatedDomainInternal = in.DeprecatedDomainInternal
	out.Address = (*duckv1alpha1.Addressable)(unsafe.Pointer(in.Address))
	if in.Traffic != nil {
		in, out := &in.Traffic, &out.Traffic
		*out = make([]serving.TrafficTarget, len(*in))
		for i := range *in {
			if err := Convert_v1alpha1_TrafficTarget_To_serving_TrafficTarget(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Traffic = nil
	}
	return nil
}

// Convert_v1alpha1_RouteStatusFields_To_serving_RouteStatusFields is an autogenerated conversion function.
func Convert_v1alpha1_RouteStatusFields_To_serving_RouteStatusFields(in *RouteStatusFields, out *serving.RouteStatusFields, s conversion.Scope) error {
	return autoConvert_v1alpha1_RouteStatusFields_To_serving_RouteStatusFields(in, out, s)
}

func autoConvert_serving_RouteStatusFields_To_v1alpha1_RouteStatusFields(in *serving.RouteStatusFields, out *RouteStatusFields, s conversion.Scope) error {
	out.URL = (*apis.URL)(unsafe.Pointer(in.URL))
	out.DeprecatedDomain = in.DeprecatedDomain
	out.DeprecatedDomainInternal = in.DeprecatedDomainInternal
	out.Address = (*duckv1alpha1.Addressable)(unsafe.Pointer(in.Address))
	if in.Traffic != nil {
		in, out := &in.Traffic, &out.Traffic
		*out = make([]TrafficTarget, len(*in))
		for i := range *in {
			if err := Convert_serving_TrafficTarget_To_v1alpha1_TrafficTarget(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Traffic = nil
	}
	return nil
}

// Convert_serving_RouteStatusFields_To_v1alpha1_RouteStatusFields is an autogenerated conversion function.
func Convert_serving_RouteStatusFields_To_v1alpha1_RouteStatusFields(in *serving.RouteStatusFields, out *RouteStatusFields, s conversion.Scope) error {
	return autoConvert_serving_RouteStatusFields_To_v1alpha1_RouteStatusFields(in, out, s)
}

func autoConvert_v1alpha1_RunLatestType_To_serving_RunLatestType(in *RunLatestType, out *serving.RunLatestType, s conversion.Scope) error {
	if err := Convert_v1alpha1_ConfigurationSpec_To_serving_ConfigurationSpec(&in.Configuration, &out.Configuration, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_RunLatestType_To_serving_RunLatestType is an autogenerated conversion function.
func Convert_v1alpha1_RunLatestType_To_serving_RunLatestType(in *RunLatestType, out *serving.RunLatestType, s conversion.Scope) error {
	return autoConvert_v1alpha1_RunLatestType_To_serving_RunLatestType(in, out, s)
}

func autoConvert_serving_RunLatestType_To_v1alpha1_RunLatestType(in *serving.RunLatestType, out *RunLatestType, s conversion.Scope) error {
	if err := Convert_serving_ConfigurationSpec_To_v1alpha1_ConfigurationSpec(&in.Configuration, &out.Configuration, s); err != nil {
		return err
	}
	return nil
}

// Convert_serving_RunLatestType_To_v1alpha1_RunLatestType is an autogenerated conversion function.
func Convert_serving_RunLatestType_To_v1alpha1_RunLatestType(in *serving.RunLatestType, out *RunLatestType, s conversion.Scope) error {
	return autoConvert_serving_RunLatestType_To_v1alpha1_RunLatestType(in, out, s)
}

func autoConvert_v1alpha1_Service_To_serving_Service(in *Service, out *serving.Service, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_ServiceSpec_To_serving_ServiceSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_ServiceStatus_To_serving_ServiceStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_Service_To_serving_Service is an autogenerated conversion function.
func Convert_v1alpha1_Service_To_serving_Service(in *Service, out *serving.Service, s conversion.Scope) error {
	return autoConvert_v1alpha1_Service_To_serving_Service(in, out, s)
}

func autoConvert_serving_Service_To_v1alpha1_Service(in *serving.Service, out *Service, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_serving_ServiceSpec_To_v1alpha1_ServiceSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_serving_ServiceStatus_To_v1alpha1_ServiceStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_serving_Service_To_v1alpha1_Service is an autogenerated conversion function.
func Convert_serving_Service_To_v1alpha1_Service(in *serving.Service, out *Service, s conversion.Scope) error {
	return autoConvert_serving_Service_To_v1alpha1_Service(in, out, s)
}

func autoConvert_v1alpha1_ServiceList_To_serving_ServiceList(in *ServiceList, out *serving.ServiceList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]serving.Service, len(*in))
		for i := range *in {
			if err := Convert_v1alpha1_Service_To_serving_Service(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Items = nil
	}
	return nil
}

// Convert_v1alpha1_ServiceList_To_serving_ServiceList is an autogenerated conversion function.
func Convert_v1alpha1_ServiceList_To_serving_ServiceList(in *ServiceList, out *serving.ServiceList, s conversion.Scope) error {
	return autoConvert_v1alpha1_ServiceList_To_serving_ServiceList(in, out, s)
}

func autoConvert_serving_ServiceList_To_v1alpha1_ServiceList(in *serving.ServiceList, out *ServiceList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Service, len(*in))
		for i := range *in {
			if err := Convert_serving_Service_To_v1alpha1_Service(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Items = nil
	}
	return nil
}

// Convert_serving_ServiceList_To_v1alpha1_ServiceList is an autogenerated conversion function.
func Convert_serving_ServiceList_To_v1alpha1_ServiceList(in *serving.ServiceList, out *ServiceList, s conversion.Scope) error {
	return autoConvert_serving_ServiceList_To_v1alpha1_ServiceList(in, out, s)
}

func autoConvert_v1alpha1_ServiceSpec_To_serving_ServiceSpec(in *ServiceSpec, out *serving.ServiceSpec, s conversion.Scope) error {
	out.DeprecatedGeneration = in.DeprecatedGeneration
	if in.DeprecatedRunLatest != nil {
		in, out := &in.DeprecatedRunLatest, &out.DeprecatedRunLatest
		*out = new(serving.RunLatestType)
		if err := Convert_v1alpha1_RunLatestType_To_serving_RunLatestType(*in, *out, s); err != nil {
			return err
		}
	} else {
		out.DeprecatedRunLatest = nil
	}
	if in.DeprecatedPinned != nil {
		in, out := &in.DeprecatedPinned, &out.DeprecatedPinned
		*out = new(serving.PinnedType)
		if err := Convert_v1alpha1_PinnedType_To_serving_PinnedType(*in, *out, s); err != nil {
			return err
		}
	} else {
		out.DeprecatedPinned = nil
	}
	out.DeprecatedManual = (*serving.ManualType)(unsafe.Pointer(in.DeprecatedManual))
	if in.DeprecatedRelease != nil {
		in, out := &in.DeprecatedRelease, &out.DeprecatedRelease
		*out = new(serving.ReleaseType)
		if err := Convert_v1alpha1_ReleaseType_To_serving_ReleaseType(*in, *out, s); err != nil {
			return err
		}
	} else {
		out.DeprecatedRelease = nil
	}
	if err := Convert_v1alpha1_ConfigurationSpec_To_serving_ConfigurationSpec(&in.ConfigurationSpec, &out.ConfigurationSpec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_RouteSpec_To_serving_RouteSpec(&in.RouteSpec, &out.RouteSpec, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_ServiceSpec_To_serving_ServiceSpec is an autogenerated conversion function.
func Convert_v1alpha1_ServiceSpec_To_serving_ServiceSpec(in *ServiceSpec, out *serving.ServiceSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_ServiceSpec_To_serving_ServiceSpec(in, out, s)
}

func autoConvert_serving_ServiceSpec_To_v1alpha1_ServiceSpec(in *serving.ServiceSpec, out *ServiceSpec, s conversion.Scope) error {
	out.DeprecatedGeneration = in.DeprecatedGeneration
	if in.DeprecatedRunLatest != nil {
		in, out := &in.DeprecatedRunLatest, &out.DeprecatedRunLatest
		*out = new(RunLatestType)
		if err := Convert_serving_RunLatestType_To_v1alpha1_RunLatestType(*in, *out, s); err != nil {
			return err
		}
	} else {
		out.DeprecatedRunLatest = nil
	}
	if in.DeprecatedPinned != nil {
		in, out := &in.DeprecatedPinned, &out.DeprecatedPinned
		*out = new(PinnedType)
		if err := Convert_serving_PinnedType_To_v1alpha1_PinnedType(*in, *out, s); err != nil {
			return err
		}
	} else {
		out.DeprecatedPinned = nil
	}
	out.DeprecatedManual = (*ManualType)(unsafe.Pointer(in.DeprecatedManual))
	if in.DeprecatedRelease != nil {
		in, out := &in.DeprecatedRelease, &out.DeprecatedRelease
		*out = new(ReleaseType)
		if err := Convert_serving_ReleaseType_To_v1alpha1_ReleaseType(*in, *out, s); err != nil {
			return err
		}
	} else {
		out.DeprecatedRelease = nil
	}
	if err := Convert_serving_ConfigurationSpec_To_v1alpha1_ConfigurationSpec(&in.ConfigurationSpec, &out.ConfigurationSpec, s); err != nil {
		return err
	}
	if err := Convert_serving_RouteSpec_To_v1alpha1_RouteSpec(&in.RouteSpec, &out.RouteSpec, s); err != nil {
		return err
	}
	return nil
}

// Convert_serving_ServiceSpec_To_v1alpha1_ServiceSpec is an autogenerated conversion function.
func Convert_serving_ServiceSpec_To_v1alpha1_ServiceSpec(in *serving.ServiceSpec, out *ServiceSpec, s conversion.Scope) error {
	return autoConvert_serving_ServiceSpec_To_v1alpha1_ServiceSpec(in, out, s)
}

func autoConvert_v1alpha1_ServiceStatus_To_serving_ServiceStatus(in *ServiceStatus, out *serving.ServiceStatus, s conversion.Scope) error {
	out.Status = in.Status
	if err := Convert_v1alpha1_RouteStatusFields_To_serving_RouteStatusFields(&in.RouteStatusFields, &out.RouteStatusFields, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_ConfigurationStatusFields_To_serving_ConfigurationStatusFields(&in.ConfigurationStatusFields, &out.ConfigurationStatusFields, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_ServiceStatus_To_serving_ServiceStatus is an autogenerated conversion function.
func Convert_v1alpha1_ServiceStatus_To_serving_ServiceStatus(in *ServiceStatus, out *serving.ServiceStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_ServiceStatus_To_serving_ServiceStatus(in, out, s)
}

func autoConvert_serving_ServiceStatus_To_v1alpha1_ServiceStatus(in *serving.ServiceStatus, out *ServiceStatus, s conversion.Scope) error {
	out.Status = in.Status
	if err := Convert_serving_RouteStatusFields_To_v1alpha1_RouteStatusFields(&in.RouteStatusFields, &out.RouteStatusFields, s); err != nil {
		return err
	}
	if err := Convert_serving_ConfigurationStatusFields_To_v1alpha1_ConfigurationStatusFields(&in.ConfigurationStatusFields, &out.ConfigurationStatusFields, s); err != nil {
		return err
	}
	return nil
}

// Convert_serving_ServiceStatus_To_v1alpha1_ServiceStatus is an autogenerated conversion function.
func Convert_serving_ServiceStatus_To_v1alpha1_ServiceStatus(in *serving.ServiceStatus, out *ServiceStatus, s conversion.Scope) error {
	return autoConvert_serving_ServiceStatus_To_v1alpha1_ServiceStatus(in, out, s)
}

func autoConvert_v1alpha1_TrafficTarget_To_serving_TrafficTarget(in *TrafficTarget, out *serving.TrafficTarget, s conversion.Scope) error {
	out.DeprecatedName = in.DeprecatedName
	// WARNING: in.TrafficTarget requires manual conversion: does not exist in peer-type
	return nil
}

func autoConvert_serving_TrafficTarget_To_v1alpha1_TrafficTarget(in *serving.TrafficTarget, out *TrafficTarget, s conversion.Scope) error {
	out.DeprecatedName = in.DeprecatedName
	// WARNING: in.Tag requires manual conversion: does not exist in peer-type
	// WARNING: in.RevisionName requires manual conversion: does not exist in peer-type
	// WARNING: in.ConfigurationName requires manual conversion: does not exist in peer-type
	// WARNING: in.LatestRevision requires manual conversion: does not exist in peer-type
	// WARNING: in.Percent requires manual conversion: does not exist in peer-type
	// WARNING: in.URL requires manual conversion: does not exist in peer-type
	return nil
}
