// +build !ignore_autogenerated

/*
Copyright 2018 Google LLC

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// This file was autogenerated by defaulter-gen. Do not edit it manually!

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// RegisterDefaults adds defaulters functions to the given scheme.
// Public to allow building arbitrary schemes.
// All generated defaulters are covering - they call all nested defaulters.
func RegisterDefaults(scheme *runtime.Scheme) error {
	scheme.AddTypeDefaultingFunc(&Configuration{}, func(obj interface{}) { SetObjectDefaults_Configuration(obj.(*Configuration)) })
	scheme.AddTypeDefaultingFunc(&ConfigurationList{}, func(obj interface{}) { SetObjectDefaults_ConfigurationList(obj.(*ConfigurationList)) })
	scheme.AddTypeDefaultingFunc(&Revision{}, func(obj interface{}) { SetObjectDefaults_Revision(obj.(*Revision)) })
	scheme.AddTypeDefaultingFunc(&RevisionList{}, func(obj interface{}) { SetObjectDefaults_RevisionList(obj.(*RevisionList)) })
	scheme.AddTypeDefaultingFunc(&Service{}, func(obj interface{}) { SetObjectDefaults_Service(obj.(*Service)) })
	scheme.AddTypeDefaultingFunc(&ServiceList{}, func(obj interface{}) { SetObjectDefaults_ServiceList(obj.(*ServiceList)) })
	return nil
}

func SetObjectDefaults_Configuration(in *Configuration) {
	SetDefaults_Configuration(in)
}

func SetObjectDefaults_ConfigurationList(in *ConfigurationList) {
	for i := range in.Items {
		a := &in.Items[i]
		SetObjectDefaults_Configuration(a)
	}
}

func SetObjectDefaults_Revision(in *Revision) {
	SetDefaults_Revision(in)
}

func SetObjectDefaults_RevisionList(in *RevisionList) {
	for i := range in.Items {
		a := &in.Items[i]
		SetObjectDefaults_Revision(a)
	}
}

func SetObjectDefaults_Service(in *Service) {
	SetDefaults_Service(in)
}

func SetObjectDefaults_ServiceList(in *ServiceList) {
	for i := range in.Items {
		a := &in.Items[i]
		SetObjectDefaults_Service(a)
	}
}
