# Copyright 2020 The Knative Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: v1
kind: ConfigMap
metadata:
  name: config-certmanager
  namespace: knative-serving
  labels:
    app.kubernetes.io/name: knative-serving
    app.kubernetes.io/component: controller
    app.kubernetes.io/version: devel
    networking.knative.dev/certificate-provider: cert-manager
  annotations:
    knative.dev/example-checksum: "b7a9a602"
data:
  _example: |
    ################################
    #                              #
    #    EXAMPLE CONFIGURATION     #
    #                              #
    ################################

    # This block is not actually functional configuration,
    # but serves to illustrate the available configuration
    # options and document them in a way that is accessible
    # to users that `kubectl edit` this config map.
    #
    # These sample configuration options may be copied out of
    # this block and unindented to actually change the configuration.

    # issuerRef is a reference to the issuer for external-domain certificates used for ingress.
    # IssuerRef should be either `ClusterIssuer` or `Issuer`.
    # Please refer `IssuerRef` in https://cert-manager.io/docs/concepts/issuer/
    # for more details about IssuerRef configuration.
    # If the issuerRef is not specified, the self-signed `knative-selfsigned-issuer` ClusterIssuer is used.
    issuerRef: |
      kind: ClusterIssuer
      name: letsencrypt-issuer

    # clusterLocalIssuerRef is a reference to the issuer for cluster-local-domain certificates used for ingress.
    # clusterLocalIssuerRef should be either `ClusterIssuer` or `Issuer`.
    # Please refer `IssuerRef` in https://cert-manager.io/docs/concepts/issuer/
    # for more details about ClusterInternalIssuerRef configuration.
    # If the clusterLocalIssuerRef is not specified, the self-signed `knative-selfsigned-issuer` ClusterIssuer is used.
    clusterLocalIssuerRef: |
      kind: ClusterIssuer
      name: your-company-issuer

    # systemInternalIssuerRef is a reference to the issuer for certificates for system-internal-tls certificates used by Knative internal components.
    # systemInternalIssuerRef should be either `ClusterIssuer` or `Issuer`.
    # Please refer `IssuerRef` in https://cert-manager.io/docs/concepts/issuer/
    # for more details about ClusterInternalIssuerRef configuration.
    # If the systemInternalIssuerRef is not specified, the self-signed `knative-selfsigned-issuer` ClusterIssuer is used.
    systemInternalIssuerRef: |
      kind: ClusterIssuer
      name: knative-selfsigned-issuer
