/*
Copyright 2018 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// This file was automatically generated by lister-gen

package v1alpha1

// ElaServiceListerExpansion allows custom methods to be added to
// ElaServiceLister.
type ElaServiceListerExpansion interface{}

// ElaServiceNamespaceListerExpansion allows custom methods to be added to
// ElaServiceNamespaceLister.
type ElaServiceNamespaceListerExpansion interface{}

// RevisionListerExpansion allows custom methods to be added to
// RevisionLister.
type RevisionListerExpansion interface{}

// RevisionNamespaceListerExpansion allows custom methods to be added to
// RevisionNamespaceLister.
type RevisionNamespaceListerExpansion interface{}

// RevisionTemplateListerExpansion allows custom methods to be added to
// RevisionTemplateLister.
type RevisionTemplateListerExpansion interface{}

// RevisionTemplateNamespaceListerExpansion allows custom methods to be added to
// RevisionTemplateNamespaceLister.
type RevisionTemplateNamespaceListerExpansion interface{}
