/*
Copyright 2022 The Knative Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	gentype "k8s.io/client-go/gentype"
	v1alpha1 "knative.dev/serving/pkg/apis/autoscaling/v1alpha1"
	autoscalingv1alpha1 "knative.dev/serving/pkg/client/clientset/versioned/typed/autoscaling/v1alpha1"
)

// fakeMetrics implements MetricInterface
type fakeMetrics struct {
	*gentype.FakeClientWithList[*v1alpha1.Metric, *v1alpha1.MetricList]
	Fake *FakeAutoscalingV1alpha1
}

func newFakeMetrics(fake *FakeAutoscalingV1alpha1, namespace string) autoscalingv1alpha1.MetricInterface {
	return &fakeMetrics{
		gentype.NewFakeClientWithList[*v1alpha1.Metric, *v1alpha1.MetricList](
			fake.Fake,
			namespace,
			v1alpha1.SchemeGroupVersion.WithResource("metrics"),
			v1alpha1.SchemeGroupVersion.WithKind("Metric"),
			func() *v1alpha1.Metric { return &v1alpha1.Metric{} },
			func() *v1alpha1.MetricList { return &v1alpha1.MetricList{} },
			func(dst, src *v1alpha1.MetricList) { dst.ListMeta = src.ListMeta },
			func(list *v1alpha1.MetricList) []*v1alpha1.Metric { return gentype.ToPointerSlice(list.Items) },
			func(list *v1alpha1.MetricList, items []*v1alpha1.Metric) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
