# Copyright 2018 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: "config.istio.io/v1alpha2"
kind: fluentd
metadata:
  name: handler
  namespace: istio-system
spec:
  address: "fluentd-es.monitoring:24224"
---
apiVersion: "config.istio.io/v1alpha2"
kind: rule
metadata:
  name: requestlogstofluentd
  namespace: istio-system
spec:
  match: "true" # match for all requests -- to filter out istio-ingress destination (as all requests hit that once), use: destination.service != "istio-ingress.istio-system.svc.cluster.local"
  actions:
   - handler: handler.fluentd
     instances:
     - requestlog.logentry
---
apiVersion: "config.istio.io/v1alpha2"
kind: logentry
metadata:
  name: requestlog
  namespace: istio-system
spec:
  severity: '"Default"'
  timestamp: request.time
  variables:
    method: request.method | ""
    url: request.path | ""
    protocol: request.scheme | "http"
    requestSize: request.size | 0
    requestHost: request.host | ""
    responseCode: response.code | 0
    responseSize: response.size | 0
    latency: response.duration | "0ms"
    sourceService: source.service | "unknown"
    destinationService: destination.service | ""
    destinationNamespace: destination.namespace | ""
    destinationRevision: destination.labels["elafros.dev/revision"] | "unknown"
    destinationConfiguration: destination.labels["elafros.dev/configuration"] | "unknown"
    traceId: request.headers["x-b3-traceid"] | "unknown"
    userAgent: request.useragent | "unknown"
    referer: request.referer | "unknown"
