# Copyright 2022 The Knative Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: v1
kind: Secret
metadata:
  # Do not drop -ctrl-ca suffix as certificate creation requires it
  # https://github.com/knative/networking/blob/main/pkg/certificates/reconciler/controller.go#L38
  name: serving-certs-ctrl-ca
  namespace: knative-serving
  labels:
    serving-certs-ctrl: "data-plane"
    networking.internal.knative.dev/certificate-uid: "serving-certs"
# The data is populated when knative-internal-tls is enabled.
---
apiVersion: v1
kind: Secret
metadata:
  # this is the legacy secret
  # we can drop this once all net-* implementations are using the new `routing-serving-certs` secret
  name: knative-serving-certs
  namespace: knative-serving
  labels:
    serving-certs-ctrl: "data-plane"
    networking.internal.knative.dev/certificate-uid: "serving-certs"
# The data is populated when knative-internal-tls is enabled.
---
apiVersion: v1
kind: Secret
metadata:
  name: routing-serving-certs
  namespace: knative-serving
  labels:
    serving-certs-ctrl: "data-plane-routing"
    networking.internal.knative.dev/certificate-uid: "serving-certs"
# The data is populated when knative-internal-tls is enabled.
