{
 "title": "Elafros - Control Plane Efficiency",
 "description": "Elafros - Control Plane Efficiency",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Namespace CPU Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"ela-system\"}[1m]))",
     "legendFormat": "ela-system"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"build-system\"}[1m]))",
     "legendFormat": "build-system"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"istio-system\"}[1m]))",
     "legendFormat": "istio-system"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"kube-system\"}[1m]))",
     "legendFormat": "kube-system"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"kube-public\"}[1m]))",
     "legendFormat": "kube-public"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"monitoring\"}[1m]))",
     "legendFormat": "monitoring"
    }
   ]
  },
  {
   "title": "Namespace Memory Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{namespace=\"ela-system\"})",
     "legendFormat": "ela-system"
    },
    {
     "expr": "sum(container_memory_usage_bytes{namespace=\"build-system\"})",
     "legendFormat": "build-system"
    },
    {
     "expr": "sum(container_memory_usage_bytes{namespace=\"istio-system\"})",
     "legendFormat": "istio-system"
    },
    {
     "expr": "sum(container_memory_usage_bytes{namespace=\"kube-system\"})",
     "legendFormat": "kube-system"
    },
    {
     "expr": "sum(container_memory_usage_bytes{namespace=\"kube-public\"})",
     "legendFormat": "kube-public"
    },
    {
     "expr": "sum(container_memory_usage_bytes{namespace=\"monitoring\"})",
     "legendFormat": "monitoring"
    }
   ]
  },
  {
   "title": "Control Plane vs Data Plane CPU Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace!~\"ela-system|monitoring|build-system|istio-system|kube-system|kube-public|^$\"}[1m]))",
     "legendFormat": "Data plane"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=~\"ela-system|monitoring|build-system|istio-system|kube-system|kube-public\"}[1m]))",
     "legendFormat": "Control plane"
    }
   ]
  },
  {
   "title": "Control Plane vs Data Plane Memory Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{namespace!~\"ela-system|monitoring|build-system|istio-system|kube-system|kube-public|^$\"})",
     "legendFormat": "Data plane"
    },
    {
     "expr": "sum(container_memory_usage_bytes{namespace=~\"ela-system|monitoring|build-system|istio-system|kube-system|kube-public\"})",
     "legendFormat": "Control plane"
    }
   ]
  }
 ]
}