/*
Copyright 2019 The Knative Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package internalversion

import (
	rest "k8s.io/client-go/rest"
	"knative.dev/serving/pkg/client/serving/clientset/internalversion/scheme"
)

type ServingInterface interface {
	RESTClient() rest.Interface
	ConfigurationsGetter
	RevisionsGetter
	RoutesGetter
	ServicesGetter
}

// ServingClient is used to interact with features provided by the serving.knative.dev group.
type ServingClient struct {
	restClient rest.Interface
}

func (c *ServingClient) Configurations(namespace string) ConfigurationInterface {
	return newConfigurations(c, namespace)
}

func (c *ServingClient) Revisions(namespace string) RevisionInterface {
	return newRevisions(c, namespace)
}

func (c *ServingClient) Routes(namespace string) RouteInterface {
	return newRoutes(c, namespace)
}

func (c *ServingClient) Services(namespace string) ServiceInterface {
	return newServices(c, namespace)
}

// NewForConfig creates a new ServingClient for the given config.
func NewForConfig(c *rest.Config) (*ServingClient, error) {
	config := *c
	if err := setConfigDefaults(&config); err != nil {
		return nil, err
	}
	client, err := rest.RESTClientFor(&config)
	if err != nil {
		return nil, err
	}
	return &ServingClient{client}, nil
}

// NewForConfigOrDie creates a new ServingClient for the given config and
// panics if there is an error in the config.
func NewForConfigOrDie(c *rest.Config) *ServingClient {
	client, err := NewForConfig(c)
	if err != nil {
		panic(err)
	}
	return client
}

// New creates a new ServingClient for the given RESTClient.
func New(c rest.Interface) *ServingClient {
	return &ServingClient{c}
}

func setConfigDefaults(config *rest.Config) error {
	config.APIPath = "/apis"
	if config.UserAgent == "" {
		config.UserAgent = rest.DefaultKubernetesUserAgent()
	}
	if config.GroupVersion == nil || config.GroupVersion.Group != scheme.Scheme.PrioritizedVersionsForGroup("serving.knative.dev")[0].Group {
		gv := scheme.Scheme.PrioritizedVersionsForGroup("serving.knative.dev")[0]
		config.GroupVersion = &gv
	}
	config.NegotiatedSerializer = scheme.Codecs

	if config.QPS == 0 {
		config.QPS = 5
	}
	if config.Burst == 0 {
		config.Burst = 10
	}

	return nil
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *ServingClient) RESTClient() rest.Interface {
	if c == nil {
		return nil
	}
	return c.restClient
}
