/*
Copyright 2022 The Knative Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1beta1

import (
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
	servingv1beta1 "knative.dev/serving/pkg/apis/serving/v1beta1"
)

// DomainMappingLister helps list DomainMappings.
// All objects returned here must be treated as read-only.
type DomainMappingLister interface {
	// List lists all DomainMappings in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*servingv1beta1.DomainMapping, err error)
	// DomainMappings returns an object that can list and get DomainMappings.
	DomainMappings(namespace string) DomainMappingNamespaceLister
	DomainMappingListerExpansion
}

// domainMappingLister implements the DomainMappingLister interface.
type domainMappingLister struct {
	listers.ResourceIndexer[*servingv1beta1.DomainMapping]
}

// NewDomainMappingLister returns a new DomainMappingLister.
func NewDomainMappingLister(indexer cache.Indexer) DomainMappingLister {
	return &domainMappingLister{listers.New[*servingv1beta1.DomainMapping](indexer, servingv1beta1.Resource("domainmapping"))}
}

// DomainMappings returns an object that can list and get DomainMappings.
func (s *domainMappingLister) DomainMappings(namespace string) DomainMappingNamespaceLister {
	return domainMappingNamespaceLister{listers.NewNamespaced[*servingv1beta1.DomainMapping](s.ResourceIndexer, namespace)}
}

// DomainMappingNamespaceLister helps list and get DomainMappings.
// All objects returned here must be treated as read-only.
type DomainMappingNamespaceLister interface {
	// List lists all DomainMappings in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*servingv1beta1.DomainMapping, err error)
	// Get retrieves the DomainMapping from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*servingv1beta1.DomainMapping, error)
	DomainMappingNamespaceListerExpansion
}

// domainMappingNamespaceLister implements the DomainMappingNamespaceLister
// interface.
type domainMappingNamespaceLister struct {
	listers.ResourceIndexer[*servingv1beta1.DomainMapping]
}
