{
 "title": "Pilot Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "content": "<center><h2>Resource Usage</h2></center>"
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "process_virtual_memory_bytes{job=\"pilot\"}",
     "legendFormat": "Virtual Memory"
    },
    {
     "expr": "process_resident_memory_bytes{job=\"pilot\"}",
     "legendFormat": "Resident Memory"
    },
    {
     "expr": "go_memstats_alloc_bytes{job=\"pilot\"}",
     "legendFormat": "Alloc"
    },
    {
     "expr": "go_memstats_heap_inuse_bytes{job=\"pilot\"}",
     "legendFormat": "Heap in-use"
    },
    {
     "expr": "go_memstats_stack_inuse_bytes{job=\"pilot\"}",
     "legendFormat": "Stack in-use"
    },
    {
     "expr": "sum(container_memory_usage_bytes{container_name=~\"discovery|istio-proxy\", pod_name=~\"istio-pilot-.*\"})",
     "legendFormat": "Total (k8s)"
    },
    {
     "expr": "container_memory_usage_bytes{container_name=~\"discovery|istio-proxy\", pod_name=~\"istio-pilot-.*\"}",
     "legendFormat": "{{ container_name }} (k8s)"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container_name=~\"discovery|istio-proxy\", pod_name=~\"istio-pilot-.*\"}[1m]))",
     "legendFormat": "Total (k8s)"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container_name=~\"discovery|istio-proxy\", pod_name=~\"istio-pilot-.*\"}[1m])) by (container_name)",
     "legendFormat": "{{ container_name }} (k8s)"
    },
    {
     "expr": "irate(process_cpu_seconds_total{job=\"pilot\"}[1m])",
     "legendFormat": "pilot (self-reported)"
    }
   ]
  },
  {
   "title": "Disk",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 3 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "container_fs_usage_bytes{container_name=~\"discovery|istio-proxy\", pod_name=~\"istio-pilot-.*\"}",
     "legendFormat": "{{ container_name }}"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_goroutines{job=\"pilot\"}",
     "legendFormat": "Number of Goroutines"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 10 },
   "content": "<center><h2>Pilot Overview</h2></center>"
  },
  {
   "title": "Discovery Calls",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(pilot_discovery_calls[1m])) by (method)",
     "legendFormat": "{{ method }}"
    }
   ]
  },
  {
   "title": "Discovery Errors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(pilot_discovery_errors[1m])) by (method)",
     "legendFormat": "{{ method }}"
    }
   ]
  },
  {
   "title": "Discovery Cache Sizes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(pilot_discovery_cache_size) by (cache_name)",
     "legendFormat": "{{ cache_name }}"
    }
   ]
  },
  {
   "title": "Discovery Returned Resource Counts",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(irate(pilot_discovery_resources_bucket[1m])) by (le, method))",
     "legendFormat": "{{ method }} -  p50"
    },
    {
     "expr": "histogram_quantile(0.9, sum(irate(pilot_discovery_resources_bucket[1m])) by (le, method))",
     "legendFormat": "{{ method }} -  p90"
    },
    {
     "expr": "histogram_quantile(0.99, sum(irate(pilot_discovery_resources_bucket[1m])) by (le, method))",
     "legendFormat": "{{ method }} -  p99"
    }
   ]
  },
  {
   "title": "CDS Cache",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(pilot_discovery_cache_hit{cache_name=\"cds\"}[1m]))",
     "legendFormat": "Hits"
    },
    {
     "expr": "sum(irate(pilot_discovery_cache_miss{cache_name=\"cds\"}[1m]))",
     "legendFormat": "MIsses"
    }
   ]
  },
  {
   "title": "LDS Cache",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(pilot_discovery_cache_hit{cache_name=\"lds\"}[1m])) ",
     "legendFormat": "Hits"
    },
    {
     "expr": "sum(irate(pilot_discovery_cache_miss{cache_name=\"lds\"}[1m])) ",
     "legendFormat": "Misses"
    }
   ]
  },
  {
   "title": "RDS Cache",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(pilot_discovery_cache_hit{cache_name=\"rds\"}[1m]))",
     "legendFormat": "Hits"
    },
    {
     "expr": "sum(irate(pilot_discovery_cache_miss{cache_name=\"rds\"}[1m]))",
     "legendFormat": "Misses"
    }
   ]
  },
  {
   "title": "SDS Cache",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(pilot_discovery_cache_hit{cache_name=\"sds\"}[1m]))",
     "legendFormat": "Hits"
    },
    {
     "expr": "sum(irate(pilot_discovery_cache_miss{cache_name=\"sds\"}[1m]))",
     "legendFormat": "Misses"
    }
   ]
  },
  {
   "title": "Cluster Membership",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "envoy_cluster_out_istio_pilot_istio_system_svc_cluster_local_http_discovery_membership_healthy",
     "legendFormat": "Discovery (Healthy)"
    },
    {
     "expr": "envoy_cluster_out_istio_pilot_istio_system_svc_cluster_local_http_discovery_membership_total",
     "legendFormat": "Discovery (Total)"
    },
    {
     "expr": "envoy_cluster_out_istio_pilot_istio_system_svc_cluster_local_admission_webhook_membership_healthy",
     "legendFormat": "Admission Webhook (Healthy)"
    },
    {
     "expr": "envoy_cluster_out_istio_pilot_istio_system_svc_cluster_local_admission_webhook_membership_total",
     "legendFormat": "Admission Webhook (Total)"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 3, "w": 24, "x": 0, "y": 34 }, "content": "<center><h2>xDS</h2></center>" },
  {
   "title": "Requests",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(envoy_cluster_cds_upstream_rq_total[1m]))",
     "legendFormat": "cds"
    },
    {
     "expr": "sum(irate(envoy_cluster_lds_upstream_rq_total[1m]))",
     "legendFormat": "lds"
    },
    {
     "expr": "sum(irate(envoy_cluster_rds_upstream_rq_total[1m]))",
     "legendFormat": "rds"
    },
    {
     "expr": "sum(irate(envoy_cluster_sds_upstream_rq_total[1m]))",
     "legendFormat": "sds"
    }
   ]
  },
  {
   "title": "Client Errors (4xxs)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(envoy_cluster_cds_upstream_rq_4xx[1m]))",
     "legendFormat": "cds"
    },
    {
     "expr": "sum(irate(envoy_cluster_lds_upstream_rq_4xx[1m]))",
     "legendFormat": "lds"
    },
    {
     "expr": "sum(irate(envoy_cluster_rds_upstream_rq_4xx[1m]))",
     "legendFormat": "rds"
    },
    {
     "expr": "sum(irate(envoy_cluster_sds_upstream_rq_4xx[1m]))",
     "legendFormat": "sds"
    }
   ]
  },
  {
   "title": "Server Errors (5xxs)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(envoy_cluster_cds_upstream_rq_5xx[1m]))",
     "legendFormat": "cds"
    },
    {
     "expr": "sum(irate(envoy_cluster_lds_upstream_rq_5xx[1m]))",
     "legendFormat": "lds"
    },
    {
     "expr": "sum(irate(envoy_cluster_rds_upstream_rq_5xx[1m]))",
     "legendFormat": "rds"
    },
    {
     "expr": "sum(irate(envoy_cluster_sds_upstream_rq_5xx[1m]))",
     "legendFormat": "sds"
    }
   ]
  },
  {
   "title": "CDS Request Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(envoy_cluster_cds_upstream_rq_time) by (quantile)",
     "legendFormat": "{{ quantile }}"
    }
   ]
  },
  {
   "title": "LDS Request Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 43 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(envoy_cluster_lds_upstream_rq_time) by (quantile)",
     "legendFormat": "{{ quantile }}"
    }
   ]
  },
  {
   "title": "RDS Request Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 43 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(envoy_cluster_rds_upstream_rq_time) by (quantile)",
     "legendFormat": "{{ quantile }}"
    }
   ]
  },
  {
   "title": "SDS Request Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 43 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(envoy_cluster_sds_upstream_rq_time) by (quantile)",
     "legendFormat": "{{ quantile }}"
    }
   ]
  },
  {
   "title": "Active Connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 50 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(envoy_cluster_cds_upstream_cx_active)",
     "legendFormat": "cds"
    },
    {
     "expr": "sum(envoy_cluster_lds_upstream_cx_active)",
     "legendFormat": "lds"
    },
    {
     "expr": "sum(envoy_cluster_rds_upstream_cx_active)",
     "legendFormat": "rds"
    },
    {
     "expr": "sum(envoy_cluster_sds_upstream_cx_active)",
     "legendFormat": "sds"
    }
   ]
  },
  {
   "title": "Cluster Membership",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 50 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(envoy_cluster_cds_membership_healthy)",
     "legendFormat": "cds (healthy)"
    },
    {
     "expr": "sum(envoy_cluster_cds_membership_total)",
     "legendFormat": "cds (total)"
    },
    {
     "expr": "sum(envoy_cluster_lds_membership_healthy)",
     "legendFormat": "lds (healthy)"
    },
    {
     "expr": "sum(envoy_cluster_lds_membership_total)",
     "legendFormat": "lds (total)"
    },
    {
     "expr": "sum(envoy_cluster_rds_membership_healthy)",
     "legendFormat": "rds (healthy)"
    },
    {
     "expr": "sum(envoy_cluster_rds_membership_total)",
     "legendFormat": "rds (total)"
    },
    {
     "expr": "sum(envoy_cluster_sds_membership_healthy)",
     "legendFormat": "sds (healthy)"
    },
    {
     "expr": "sum(envoy_cluster_sds_membership_total)",
     "legendFormat": "sds (total)"
    }
   ]
  }
 ]
}