apiVersion: cloudbuild.googleapis.com/v1alpha1
kind: BuildTemplate
metadata:
  name: buildpack
spec:
  parameters:
  - name: IMAGE
    description: The name of the image to push
  - name: DIRECTORY
    description: The directory containing the app
    default: /workspace
  - name: CACHE
    description: The name of the persistent app cache volume
    default: app-cache

  steps:
  - name: build
    image: packs/cf:build-v4
    workingdir: "${DIRECTORY}"
    env:
    volumeMounts:
    - name: droplet
      mountPath: /out
    - name: app-cache # "${CACHE}" doesn't work
      mountPath: /cache

  - name: export
    image: packs/cf:export-v4
    workingdir: /in
    args: ["${IMAGE}"]
    env:
    - name: DOCKER_CONFIG
      value: /root/.docker
    volumeMounts:
    - name: droplet
      mountPath: /in
    - name: docker-socket
      mountPath: /var/run/docker.sock

  volumes:
  - name: droplet
    emptyDir: {}
  - name: app-cache
    emptyDir: {}
  - name: docker-socket
    hostPath:
      path: /var/run/docker.sock
      type: Socket
