apiVersion: build.dev/v1alpha1
kind: BuildTemplate
metadata:
  name: buildpack
spec:
  parameters:
  - name: IMAGE
    description: The name of the image to push
  - name: BUILDPACK_ORDER
    description: A comma separated list of names or URLs for the buildpacks to use. Each buildpack is applied in order.
    default: ""
  - name: SKIP_DETECT
    description: By default, the first buildpack to match is used. If true, detection is skipped and each buildpack contributes in order.
    default: "false"
  - name: DIRECTORY
    description: The directory containing the app
    default: /workspace
  - name: CACHE
    description: The name of the persistent app cache volume
    default: app-cache

  steps:
  # In: a CF app in $DIRECTORY
  # Out: a CF app droplet in /out
  # Out: a build cache in /cache
  - name: build
    image: packs/cf:build
    args: ["-skipDetect=${SKIP_DETECT}", "-buildpackOrder=${BUILDPACK_ORDER}"]
    workingdir: "${DIRECTORY}"
    volumeMounts:
    - name: droplet
      mountPath: /out
    - name: "${CACHE}"
      mountPath: /cache

  # In: a CF app droplet in /in
  # Out: an image published as $IMAGE
  - name: export
    image: packs/cf:export
    workingdir: /in
    args: ["${IMAGE}"]
    env:
    - name: PACK_REGISTRY_GCR
      value: "true"
    volumeMounts:
    - name: droplet
      mountPath: /in

  volumes:
  - name: droplet
    emptyDir: {}
  - name: app-cache
    emptyDir: {}
