{
 "title": "Knative Serving - Scaling Debugging",
 "description": "Knative Serving - Scaling Debugging",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(autoscaler_observed_pod_count, namespace_name)"
   },
   {
    "name": "configuration",
    "label": "Configuration",
    "query": "label_values(autoscaler_observed_pod_count{namespace_name=\"$namespace\"}, configuration_name)"
   },
   {
    "name": "revision",
    "label": "Revision",
    "query": "label_values(autoscaler_observed_pod_count{namespace_name=\"$namespace\", configuration_name=\"$configuration\"}, revision_name)"
   }
  ]
 },
 "panels": [
  {
   "title": "Revision Pod Counts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Revision Pod Counts",
     "type": "graph",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(autoscaler_actual_pod_count{namespace_name=\"$namespace\", configuration_name=\"$configuration\", revision_name=\"$revision\"})",
       "legendFormat": "Actual Pods"
      },
      {
       "expr": "sum(autoscaler_requested_pod_count{namespace_name=\"$namespace\", configuration_name=\"$configuration\", revision_name=\"$revision\"})",
       "legendFormat": "Requested Pods"
      }
     ]
    }
   ]
  },
  {
   "title": "Resource Usages",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Revision CPU Usage",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(kube_pod_container_resource_requests_cpu_cores{namespace=\"$namespace\", pod=~\"$revision-deployment-.*\"})",
       "legendFormat": "Cores requested"
      },
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", pod_name=~\"$revision-deployment-.*\"}[1m]))",
       "legendFormat": "Cores used"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits_cpu_cores{namespace=\"$namespace\", pod=~\"$revision-deployment-.*\"})",
       "legendFormat": "Core limit"
      }
     ]
    },
    {
     "title": "Pod Memory Usage",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 13 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "sum(kube_pod_container_resource_requests_memory_bytes{namespace=\"$namespace\", pod=~\"$revision-deployment-.*\"})",
       "legendFormat": "Memory requested"
      },
      {
       "expr": "sum(container_memory_usage_bytes{namespace=\"$namespace\", pod_name=~\"$revision-deployment-.*\"})",
       "legendFormat": "Memory used"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits_memory_bytes{namespace=\"$namespace\", pod=~\"$revision-deployment-.*\"})"
      }
     ]
    }
   ]
  },
  {
   "title": "Autoscaler Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Pod Counts",
     "type": "graph",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(autoscaler_desired_pod_count{namespace_name=\"$namespace\", configuration_name=\"$configuration\", revision_name=\"$revision\"}) ",
       "legendFormat": "Desired Pods"
      },
      {
       "expr": "sum(autoscaler_observed_pod_count{namespace_name=\"$namespace\", configuration_name=\"$configuration\", revision_name=\"$revision\"})",
       "legendFormat": "Observed Pods"
      }
     ]
    },
    {
     "title": "Observed Concurrency",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(autoscaler_observed_stable_concurrency{namespace_name=\"$namespace\", configuration_name=\"$configuration\", revision_name=\"$revision\"})",
       "legendFormat": "60 Second Average Concurrency"
      },
      {
       "expr": "sum(autoscaler_observed_panic_concurrency{namespace_name=\"$namespace\", configuration_name=\"$configuration\", revision_name=\"$revision\"})",
       "legendFormat": "6 Second Average Panic Concurrency"
      },
      {
       "expr": "sum(autoscaler_target_concurrency_per_pod{namespace_name=\"$namespace\", configuration_name=\"$configuration\", revision_name=\"$revision\"})",
       "legendFormat": "60 Second Target Concurrency"
      }
     ]
    },
    {
     "title": "Panic Mode",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(autoscaler_panic_mode{namespace_name=\"$namespace\", configuration_name=\"$configuration\", revision_name=\"$revision\"} )",
       "legendFormat": "Panic Mode"
      }
     ]
    }
   ]
  },
  {
   "title": "Activator Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Request Count in last minute by Response Code",
     "type": "graph",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "round(sum(increase(activator_revision_request_count{namespace_name=\"$namespace\", configuration_name=~\"$configuration\",revision_name=~\"$revision\"}[1m])) by (response_code))",
       "legendFormat": "{{ response_code }}"
      }
     ]
    },
    {
     "title": "Response Time in last minute",
     "type": "graph",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 32 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "label_replace(histogram_quantile(0.50, sum(rate(activator_response_time_msec_bucket{namespace_name=\"$namespace\", configuration_name=~\"$configuration\",revision_name=~\"$revision\"}[1m])) by (revision_name, le)), \"revision_name\", \"$2\", \"revision_name\", \"$configuration(-+)(.*)\")",
       "legendFormat": "{{ revision_name }} (p50)"
      },
      {
       "expr": "label_replace(histogram_quantile(0.90, sum(rate(activator_response_time_msec_bucket{namespace_name=\"$namespace\", configuration_name=~\"$configuration\",revision_name=~\"$revision\"}[1m])) by (revision_name, le)), \"revision_name\", \"$2\", \"revision_name\", \"$configuration(-+)(.*)\")",
       "legendFormat": "{{ revision_name }} (p90)"
      },
      {
       "expr": "label_replace(histogram_quantile(0.95, sum(rate(activator_response_time_msec_bucket{namespace_name=\"$namespace\", configuration_name=~\"$configuration\",revision_name=~\"$revision\"}[1m])) by (revision_name, le)), \"revision_name\", \"$2\", \"revision_name\", \"$configuration(-+)(.*)\")",
       "legendFormat": "{{ revision_name }} (p95)"
      },
      {
       "expr": "label_replace(histogram_quantile(0.99, sum(rate(activator_response_time_msec_bucket{namespace_name=\"$namespace\", configuration_name=~\"$configuration\",revision_name=~\"$revision\"}[1m])) by (revision_name, le)), \"revision_name\", \"$2\", \"revision_name\", \"$configuration(-+)(.*)\")",
       "legendFormat": "{{ revision_name }} (p99)"
      }
     ]
    }
   ]
  }
 ]
}