/*
Copyright 2026 The Knative Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.23.3
// source: pkg/autoscaler/metrics/stat.proto

package metrics

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Stat defines a single measurement at a point in time.
type Stat struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The unique identity of this pod.  Used to count how many pods
	// are contributing to the metrics.
	PodName string `protobuf:"bytes,1,opt,name=pod_name,json=podName,proto3" json:"pod_name,omitempty"`
	// Average number of requests currently being handled by this pod.
	AverageConcurrentRequests float64 `protobuf:"fixed64,2,opt,name=average_concurrent_requests,json=averageConcurrentRequests,proto3" json:"average_concurrent_requests,omitempty"`
	// Part of AverageConcurrentRequests, for requests going through a proxy.
	AverageProxiedConcurrentRequests float64 `protobuf:"fixed64,3,opt,name=average_proxied_concurrent_requests,json=averageProxiedConcurrentRequests,proto3" json:"average_proxied_concurrent_requests,omitempty"`
	// Number of requests received since last Stat (approximately requests per second).
	RequestCount float64 `protobuf:"fixed64,4,opt,name=request_count,json=requestCount,proto3" json:"request_count,omitempty"`
	// Part of RequestCount, for requests going through a proxy.
	ProxiedRequestCount float64 `protobuf:"fixed64,5,opt,name=proxied_request_count,json=proxiedRequestCount,proto3" json:"proxied_request_count,omitempty"`
	// Process uptime in seconds.
	ProcessUptime float64 `protobuf:"fixed64,6,opt,name=process_uptime,json=processUptime,proto3" json:"process_uptime,omitempty"`
	// Time/date that the stat was generated in seconds since
	// 1970-01-01 00:00:00.000 UTC.
	Timestamp     int64 `protobuf:"varint,7,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Stat) Reset() {
	*x = Stat{}
	mi := &file_pkg_autoscaler_metrics_stat_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Stat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Stat) ProtoMessage() {}

func (x *Stat) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_autoscaler_metrics_stat_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Stat.ProtoReflect.Descriptor instead.
func (*Stat) Descriptor() ([]byte, []int) {
	return file_pkg_autoscaler_metrics_stat_proto_rawDescGZIP(), []int{0}
}

func (x *Stat) GetPodName() string {
	if x != nil {
		return x.PodName
	}
	return ""
}

func (x *Stat) GetAverageConcurrentRequests() float64 {
	if x != nil {
		return x.AverageConcurrentRequests
	}
	return 0
}

func (x *Stat) GetAverageProxiedConcurrentRequests() float64 {
	if x != nil {
		return x.AverageProxiedConcurrentRequests
	}
	return 0
}

func (x *Stat) GetRequestCount() float64 {
	if x != nil {
		return x.RequestCount
	}
	return 0
}

func (x *Stat) GetProxiedRequestCount() float64 {
	if x != nil {
		return x.ProxiedRequestCount
	}
	return 0
}

func (x *Stat) GetProcessUptime() float64 {
	if x != nil {
		return x.ProcessUptime
	}
	return 0
}

func (x *Stat) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// WireStatMessage is a copy of the StatMessage Golang type, exploding the fields of
// `types.NamespacedName` to make it compatible with protobufs.
type WireStatMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Namespace is the namespace of the entity the stat belongs to.
	Namespace string `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	// Name is the name of the entity the stat belongs to.
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// Stat are the actual metrics being sent.
	Stat          *Stat `protobuf:"bytes,3,opt,name=stat,proto3" json:"stat,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WireStatMessage) Reset() {
	*x = WireStatMessage{}
	mi := &file_pkg_autoscaler_metrics_stat_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WireStatMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WireStatMessage) ProtoMessage() {}

func (x *WireStatMessage) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_autoscaler_metrics_stat_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WireStatMessage.ProtoReflect.Descriptor instead.
func (*WireStatMessage) Descriptor() ([]byte, []int) {
	return file_pkg_autoscaler_metrics_stat_proto_rawDescGZIP(), []int{1}
}

func (x *WireStatMessage) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *WireStatMessage) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *WireStatMessage) GetStat() *Stat {
	if x != nil {
		return x.Stat
	}
	return nil
}

// WireStatMessages is a wrapper to send multiple WireStatMessages at once.
type WireStatMessages struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Messages is a list of WireStatMessages.
	Messages      []*WireStatMessage `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WireStatMessages) Reset() {
	*x = WireStatMessages{}
	mi := &file_pkg_autoscaler_metrics_stat_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WireStatMessages) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WireStatMessages) ProtoMessage() {}

func (x *WireStatMessages) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_autoscaler_metrics_stat_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WireStatMessages.ProtoReflect.Descriptor instead.
func (*WireStatMessages) Descriptor() ([]byte, []int) {
	return file_pkg_autoscaler_metrics_stat_proto_rawDescGZIP(), []int{2}
}

func (x *WireStatMessages) GetMessages() []*WireStatMessage {
	if x != nil {
		return x.Messages
	}
	return nil
}

var File_pkg_autoscaler_metrics_stat_proto protoreflect.FileDescriptor

const file_pkg_autoscaler_metrics_stat_proto_rawDesc = "" +
	"\n" +
	"!pkg/autoscaler/metrics/stat.proto\x12\ametrics\"\xce\x02\n" +
	"\x04Stat\x12\x19\n" +
	"\bpod_name\x18\x01 \x01(\tR\apodName\x12>\n" +
	"\x1baverage_concurrent_requests\x18\x02 \x01(\x01R\x19averageConcurrentRequests\x12M\n" +
	"#average_proxied_concurrent_requests\x18\x03 \x01(\x01R averageProxiedConcurrentRequests\x12#\n" +
	"\rrequest_count\x18\x04 \x01(\x01R\frequestCount\x122\n" +
	"\x15proxied_request_count\x18\x05 \x01(\x01R\x13proxiedRequestCount\x12%\n" +
	"\x0eprocess_uptime\x18\x06 \x01(\x01R\rprocessUptime\x12\x1c\n" +
	"\ttimestamp\x18\a \x01(\x03R\ttimestamp\"f\n" +
	"\x0fWireStatMessage\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12!\n" +
	"\x04stat\x18\x03 \x01(\v2\r.metrics.StatR\x04stat\"H\n" +
	"\x10WireStatMessages\x124\n" +
	"\bmessages\x18\x01 \x03(\v2\x18.metrics.WireStatMessageR\bmessagesB,Z*knative.dev/serving/pkg/autoscaler/metricsb\x06proto3"

var (
	file_pkg_autoscaler_metrics_stat_proto_rawDescOnce sync.Once
	file_pkg_autoscaler_metrics_stat_proto_rawDescData []byte
)

func file_pkg_autoscaler_metrics_stat_proto_rawDescGZIP() []byte {
	file_pkg_autoscaler_metrics_stat_proto_rawDescOnce.Do(func() {
		file_pkg_autoscaler_metrics_stat_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_autoscaler_metrics_stat_proto_rawDesc), len(file_pkg_autoscaler_metrics_stat_proto_rawDesc)))
	})
	return file_pkg_autoscaler_metrics_stat_proto_rawDescData
}

var file_pkg_autoscaler_metrics_stat_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_pkg_autoscaler_metrics_stat_proto_goTypes = []any{
	(*Stat)(nil),             // 0: metrics.Stat
	(*WireStatMessage)(nil),  // 1: metrics.WireStatMessage
	(*WireStatMessages)(nil), // 2: metrics.WireStatMessages
}
var file_pkg_autoscaler_metrics_stat_proto_depIdxs = []int32{
	0, // 0: metrics.WireStatMessage.stat:type_name -> metrics.Stat
	1, // 1: metrics.WireStatMessages.messages:type_name -> metrics.WireStatMessage
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_pkg_autoscaler_metrics_stat_proto_init() }
func file_pkg_autoscaler_metrics_stat_proto_init() {
	if File_pkg_autoscaler_metrics_stat_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_autoscaler_metrics_stat_proto_rawDesc), len(file_pkg_autoscaler_metrics_stat_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_autoscaler_metrics_stat_proto_goTypes,
		DependencyIndexes: file_pkg_autoscaler_metrics_stat_proto_depIdxs,
		MessageInfos:      file_pkg_autoscaler_metrics_stat_proto_msgTypes,
	}.Build()
	File_pkg_autoscaler_metrics_stat_proto = out.File
	file_pkg_autoscaler_metrics_stat_proto_goTypes = nil
	file_pkg_autoscaler_metrics_stat_proto_depIdxs = nil
}
