---
apiVersion: elafros.dev/v1alpha1
kind: Route
metadata:
  name: grpc-ping
  namespace: default
spec:
  traffic:
  - configurationName: grpc-ping
    percent: 100
---
apiVersion: elafros.dev/v1alpha1
kind: Configuration
metadata:
  name: grpc-ping
  namespace: default
spec:
  revisionTemplate:
    metadata:
      labels:
        elafros.dev/type: app
    spec:
      protocol: grpc
      container:
        image: github.com/elafros/elafros/sample/grpc-ping
