name: Knative Dev CI/CD
on:
  pull_request:
    branches:
      - release-*
  push:
    branches:
      - development

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        component:
          - name: activator
            path: ./cmd/activator
          - name: autoscaler
            path: ./cmd/autoscaler
          - name: queue
            path: ./cmd/queue
          - name: webhook
            path: ./cmd/webhook
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"

      - name: Install ko
        uses: ko-build/setup-ko@v0.6

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - uses: depot/setup-action@v1

      - name: Build and Push ${{ matrix.component.name }}
        env:
          KO_DOCKER_REPO: ${{ steps.login-ecr.outputs.registry }}/knative-${{ matrix.component.name }}-dev-virginia
          DEPOT_TOKEN: ${{ secrets.DEPOT_TOKEN }}
        run: |
          ko build --bare --platform=linux/amd64,linux/arm64 --tags=dev ${{ matrix.component.path }}

  notify:
    needs: build
    runs-on: ubuntu-latest
    if: always() && needs.build.result == 'success'
    steps:
      - name: Notify Slack!
        uses: someimportantcompany/github-actions-slack-message@v1
        with:
          webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}
          text: ":rocket: Knative components built and pushed to dev registry! :rocket:"
