# Copyright 2020 The Knative Authors.
# SPDX-License-Identifier: Apache-2.0

# This file is automagically synced here from github.com/knative-sandbox/knobots

name: Build

on:
  pull_request:
    branches: [ 'main', 'release-*' ]

permissions:
  contents: read

jobs:
  build:
    permissions:
      contents: none
    uses: knative/actions/.github/workflows/go-build.yaml@main
