# Copyright 2020 The Knative Authors.
# SPDX-License-Identifier: Apache-2.0

# This file is automagically synced here from github.com/knative-sandbox/knobots

name: 'Release Notes'

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch'
        required: true
        default: 'main'
      start-rev:
        description: 'Start Tag (defaults to merge-base(branch, prev-branch))'
        required: false
      end-rev:
        description: 'End Tag (defaults to HEAD of the target branch)'
        required: false

jobs:
  release-notes:
    uses: knative/actions/.github/workflows/release-notes.yaml@main
    with:
      branch: ${{ github.event.inputs.branch }}
      start-rev: ${{ github.event.inputs.start-rev }}
      end-rev: ${{ github.event.inputs.end-rev }}
